### ISSUE TITLE
Binary-based scanner

### ISSUE THREAD

**Issue by wlxo0401** [Wooder/ios_17_required_reason_api_scanner#11]
<img width="496" alt="image" src="https://github.com/Wooder/ios_17_required_reason_api_scanner/assets/57979066/0d39296b-4beb-432e-a69b-ba10e136b2ff">

1. What do you mean by SDKs that come out empty like in the picture??? 

2. I use a library like Toast-Swift and it's not included in 'binaryies'. Is it included only if it's a framework??

**Comment by crasowas** [comment]
1. The output is empty, which means no symbols were scanned in the binary file.
2. The framework is not required, it will scan all binary files in the path. For libraries like `Toast-Swift` that do not include binaries, you can try using `required_reason_api_text_scanner.sh`.
