### ISSUE TITLE
The ISSUES email sent by App Store Connect has detailed information

### ISSUE THREAD

**Issue by diamont1001** [Wooder/ios_17_required_reason_api_scanner#17]
It's awesome for creating this. Thank you!

But you can try submitting a new version to the App Store for review, and you will receive an email containing the APIType you need to add.

![image](https://github.com/Wooder/ios_17_required_reason_api_scanner/assets/7159888/fb7bfcc3-e389-4514-bcfe-062b1834dd2a)

**Comment by Wooder** [comment]
You are right about that - the scanner helps to display ALL instances in the code that use "Required Reason API" before transmission, thus determining the correct justification (e.g., CA92.1). 

However, especially in larger commercial projects (with strict release schedules), one might want to ensure before uploading the app to App Store Connect that no "new" use of "Required Reason API" has been added to the source code without adjusting the Privacy Manifest.
