### ISSUE TITLE
Thank you for creating this

### ISSUE THREAD

**Issue by NorseGaud** [Wooder/ios_17_required_reason_api_scanner#9]
Just wanted to say that you're awesome for creating this. Thank you!

**Comment by gkasireddy202** [comment]
@NorseGaud  - How to download sh required_reason_api_scanner.sh YourAppDirectory and run in your react-native project?

**Comment by wlxo0401** [comment]
@gkasireddy202 

When you download and decompress the GitHub file, there are two .sh files. 

Use it as stated in ReadME.

**Comment by gkasireddy202** [comment]
@wlxo0401  - Thanks it is working.

**Comment by gkasireddy202** [comment]
In my project, I am using the react-native-document-picker,react-native-sqlite-storage, and react-native-calendars.
 required_reason_api_scanner.sh scanner does not show the line numbers for the above libraries.
You don't need to add manifest files for the above third-party libraries. right?
Showing line numbers for the below ones.
react-native-signature-capture
react-native-permissions,
react-native-image-crop-picker.

**Comment by NorseGaud** [comment]
If you guys are going to rudely use this as a way for you to get help, I'll just close it. Way to ruin a good thing...
